name: Docker Build and Push

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t <dockerhubaccount>/CA3:latest .

    - name: Push Docker image to Docker Hub
      run: docker push <dockerhubaccount>/CA3:latest
